version: 2.1

jobs:
  build:
    working_directory: ~/js-sona-types
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: build
          command: yarn build
      - run:
          name: test examples
          command: yarn ci
      - run:
          name: scan project
          command: npx auditjs@latest ossi -q
      - run:
          name: scan node example
          command: |
            cd examples/node
            npx auditjs@latest ossi -q
      - run:
          name: scan react example
          command: |
            cd examples/react-test-app
            npx auditjs@latest ossi -q
      - run:
          name: scan node ts example
          command: |
            cd examples/node-ts
            npx auditjs@latest ossi -q

  release:
    working_directory: ~/js-sona-types
    docker:
      - image: circleci/node:14.17.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build js-sona-types
          command: yarn build
      - run:
          name: Install globals
          command: yarn global add semantic-release@beta @semantic-release/changelog @semantic-release/git@beta @semantic-release/npm@beta
      - run:
          name: Publish
          command: yarn exec semantic-release

workflows:
  version: 2.1
  build_and_release:
    jobs:
      - build
      - release:
          filters:
            branches:
              only: main
          context: auditjs
          requires:
            - build

  build_nightly:
    triggers:
      - schedule:
          cron: "40 20 * * *"
          filters:
            branches:
              only: main
    jobs:
      - build
